default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: travel_companion_development

test:
  <<: *default
  database: travel_companion_test

production:
  <<: *default
  database: travel_companion_production
  username: travel_companion_db
  password: your_database_password
