default: &default
  source_path: app/javascript
  source_entry_path: packs
  public_root_path: public
  public_output_path: packs
  cache_path: tmp/cache/webpacker
  extensions:
    - .jsx
    - .js
    - .sass
    - .scss
    - .css
    - .module.sass
    - .module.scss
    - .module.css
    - .png
    - .svg
    - .gif
    - .jpeg
    - .jpg

development:
  <<: *default
  compile: true

  dev_server:
    host: localhost
    port: 3000
    https: false
    hmr: false
    public: localhost:3035
    # hot_only: true

test:
  <<: *default
  compile: true

  dev_server:
    host: localhost
    port: 3000
    https: false

production:
  <<: *default
  compile: false
  extract_css: true
  cache_manifest: true
